env:
  browser: true
  es2021: true
  "vue/setup-compiler-macros": true
extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-essential"
  - "@vue/eslint-config-typescript/recommended"
  - "@vue/eslint-config-prettier"
parserOptions:
  ecmaVersion: 12
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {
  "prettier/prettier": "off"
}
